Repository JoinMarket-Org/joinmarket-clientserver, pull requests merged in 2022-10, with the labels that each got.

#1361 Allow to run `install.sh` from any current working directory
  install.sh
Labels: Installation

#1365 Allow amounts below `DUST_THRESHOLD` (0.00027300 BTC) for non-cj direct sends
  scripts/joinmarket-qt.py
  scripts/sendpayment.py
Labels: enhancement

#1364 Minor improvements for `install.sh` question prompts and feedback
  install.sh
Labels: Installation

#1374 Change payjoin default binding port
  docs/PAYJOIN.md
  jmclient/jmclient/configure.py
  test/payjoinclient.py
  test/payjoinserver.py
Labels: enhancement

#1301 ob-watcher: tackle stale orders by first removing all of them
  scripts/obwatch/ob-watcher.py
Labels: bug
