Repository JoinMarket-Org/joinmarket-clientserver, pull requests merged in 2022-12, with the labels that each got.

#1402 Trivial: Fix typo in `gettimelockaddress`
  docs/fidelity-bonds.md
  jmclient/jmclient/wallet_utils.py
Labels: documentation

#1409 CI: Remove Python 3.6 (EOL), add 3.10
  .github/workflows/unittests.yml
Labels: Testing

#1408 Update local Tor to 0.4.7.12
  install.sh
Labels: dependencies

#1398 Pin remaining deps to specific versions, except for Qt and tests
  jmbase/setup.py
  jmbitcoin/setup.py
  jmclient/setup.py
  jmdaemon/setup.py
Labels: dependencies

#1348 Abort sync_unspent if blockheight RPC call fails
  jmclient/jmclient/wallet_service.py
Labels: bug

#1396 Use python3's venv module instead of virtualenv
  docs/INSTALL.md
  docs/TESTING.md
  docs/onion-message-channels.md
  install.sh
  jmclient/jmclient/wallet_utils.py
  scripts/obwatch/ob-watcher.py
  test/Dockerfiles/bionic-py3.Dockerfile
  test/Dockerfiles/centos7-py3.Dockerfile
  test/Dockerfiles/fedora27-py3.Dockerfile
  test/Dockerfiles/stretch-py3.Dockerfile
  test/Dockerfiles/xenial-py3.Dockerfile
  test/run_tests.sh
Labels: dependencies, Installation

#1412 CI: Run tests on both Linux and macOS
  .github/workflows/unittests.yml
  test/testrunner/install_bitcoind.sh
Labels: Testing

#1414 Apply all current ShellCheck suggestions and add `lint-shell.sh`
  install.sh
  scripts/joinmarket-qt.sh
  test/Dockerfiles/build_docker.sh
  test/lint/lint-all.sh
  test/lint/lint-python.sh
  test/lint/lint-shell.sh
  test/run_tests.sh
Labels: Testing
