Repository JoinMarket-Org/joinmarket-clientserver, pull requests merged in 2023-01, with the labels that each got.

#1427 Test: refactor `conftest.py`
  conftest.py
Labels: Testing

#1431 Update local Tor to 0.4.7.13
  install.sh
Labels: dependencies

#1423 Keep trying to receive websocket notification in test
  jmclient/test/test_wallet_rpc.py
Labels: Testing

#1433 Tests: Use different jm_test_datadir for each local user
  test/run_tests.sh
Labels: Testing

#1437 Add link to my public orderbook mirror
  README.md
Labels: documentation

#1432 tests: make setup fixtures optional.
  conftest.py
  jmclient/test/test_blockchaininterface.py
  jmclient/test/test_bond_calc.py
  jmclient/test/test_client_protocol.py
  jmclient/test/test_coinjoin.py
  jmclient/test/test_commitment_utils.py
  jmclient/test/test_configure.py
  jmclient/test/test_core_nohistory_sync.py
  jmclient/test/test_payjoin.py
  jmclient/test/test_podle.py
  jmclient/test/test_privkeys.py
  jmclient/test/test_psbt_wallet.py
  jmclient/test/test_schedule.py
  jmclient/test/test_snicker.py
  jmclient/test/test_taker.py
  jmclient/test/test_tx_creation.py
  jmclient/test/test_valid_addresses.py
  jmclient/test/test_wallet.py
  jmclient/test/test_wallet_rpc.py
  jmclient/test/test_wallets.py
  jmclient/test/test_walletservice.py
  jmclient/test/test_walletutils.py
  jmclient/test/test_yieldgenerator.py
  jmdaemon/test/test_daemon_protocol.py
  jmdaemon/test/test_irc_messaging.py
  jmdaemon/test/test_orderbookwatch.py
  test/test_e2e_coinjoin.py
Labels: Testing

#1438 Tests: bind to any first free TCP ports instead of hardcoded ones
  jmbase/jmbase/support.py
  jmclient/test/test_wallet_rpc.py
  jmclient/test/test_websocket.py
Labels: Testing

#1428 Support Python 3.11 and add it to CI
  .github/workflows/unittests.yml
  jmclient/setup.py
Labels: Testing, dependencies, Installation
