Repository JoinMarket-Org/joinmarket-clientserver, pull requests merged in 2023-10, with the labels that each got.

#1567 Update `txtorcon` to 23.0.0
  pyproject.toml
Labels: dependencies

#1579 Bump `cryptography` to 41.0.4 for all platforms
  pyproject.toml
Labels: dependencies

#1580 CI: Update Bitcoin Core from 25.0 to 25.1 and disable venv caching
  .github/workflows/unittests.yml
Labels: Testing

#1590 fix Dockerfile gpg err
  Dockerfile
Labels: Installation

#1591 Fix ShellCheck warnings and add ShellCheck to CI
  .github/workflows/unittests.yml
  test/run_tests.sh
  test/testrunner/install_bitcoind.sh
Labels: Testing

#1577 feat(rpc): add block height to session response
  docs/api/wallet-rpc.yaml
  src/jmclient/wallet_rpc.py
Labels: RPC-API
