Repository JoinMarket-Org/joinmarket-clientserver, pull requests merged in 2023-08, with the labels that each got.

#1512 Drop Python 3.6 support
  README.md
  docs/INSTALL.md
  jmbase/setup.py
  jmbitcoin/setup.py
  jmclient/setup.py
  jmdaemon/setup.py
  jmqtui/setup.py
  setupall.py
Labels: dependencies

#1218 GitHub workflow update (test multiple Bitcoin Core versions)
  .github/workflows/unittests.yml
  test/testrunner/install_bitcoind.sh
Labels: Testing

#1525 RPC-API: read gaplimit from config
  jmclient/jmclient/configure.py
  jmclient/jmclient/wallet_rpc.py
  jmclient/jmclient/wallet_utils.py
Labels: RPC-API
