Repository JoinMarket-Org/joinmarket-clientserver, pull requests merged in 2024-02, with the labels that each got.

#1648 When looking for a free TCP ports, bind only to localhost
  src/jmbase/support.py
Labels: Testing

#1651 Bump txtorcon from 23.0.0 to 23.11.0
  pyproject.toml
Labels: dependencies

#1649 Add GitHub CodeQL code scanning
  .github/workflows/codeql.yml
Labels: Testing

#1657 Remove `--disable-jni` from `libsecp256k1_build`
  install.sh
Labels: dependencies, Installation

#1665 Qt: Fix no amount entered message (can be sats too, not only BTC)
  scripts/joinmarket-qt.py
Labels: Joinmarket-Qt

#1668 update payjoin doc
  docs/PAYJOIN.md
Labels: documentation

#1670 Bump pyopenssl from 23.2.0 to 24.0.0
  pyproject.toml
Labels: dependencies

#1656 Tell libsodium not to download code from savannah.gnu.org in `autogen.sh`
  install.sh
Labels: Installation
