Repository JoinMarket-Org/joinmarket-clientserver, pull requests merged in 2024-01, with the labels that each got.

#1627 Fix tests for Core v26 when user has no access to `~/.bitcoin/settings.json`
  conftest.py
  test/run_tests.sh
Labels: Testing

#1638 Remove unnecessary check for Python 3.7+
  scripts/obwatch/ob-watcher.py
Labels: dependencies

#1640 CI: Add OpenAPI Diff action
  .github/workflows/openapi-diff.yml
Labels: Testing, RPC-API

#1642 Update secp256k1 lib deps for python-bitcointx 1.1.5
  pyproject.toml
  src/jmbitcoin/secp256k1_main.py
Labels: dependencies

#1612 RPC API: Add optional txfee property for single joins
  docs/api/wallet-rpc.yaml
  src/jmclient/wallet_rpc.py
Labels: RPC-API

#1645 Qt: Remove donation link from "About" dialog
  docs/JOINMARKET-QT-GUIDE.md
  scripts/joinmarket-qt.py
Labels: Joinmarket-Qt

#1639 Drop Python 3.7 support
  .github/workflows/unittests.yml
  README.md
  docs/INSTALL.md
  pyproject.toml
Labels: dependencies
